[package]
name = "scale_trainer"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
midir = "0.9.1"
serde = "1.0.188"
tokio = {version="1.32.0", features=["full"]}
